# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83467004e053f3c474ead7587bbb9b340bf5eb2d64b5f3910d6ca355374f7e6b1adcef432b720a67a578ae37d3a432c27f3e45b57ccc9b06f565a7b96112b884

test:
  secret_key_base: d059a6462b6f567798c6a00d5c3f91d6fbfdda502490082de2f40c3191df24724576358b3e5f270120fb694de92f030de36495417485d526772b2abf97bffe4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
